/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Only says the process is up.
         *
         *     The container healthcheck calls this. If it also checked Postgres then a database restart
         *     would make Docker kill an API that was working fine.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search
         * @description One search. There is no second endpoint for briefs, see docs/adr/0004.
         */
        post: operations["search_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/{media_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Media */
        get: operations["read_media_media__media_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/probes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Probes
         * @description The 23 probes with the accuracy each one was measured at.
         */
        get: operations["list_probes_probes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Suggest
         * @description Type-ahead over the tag vocabulary. Prefix matches first, then anything containing it.
         */
        get: operations["suggest_suggest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HitOut */
        HitOut: {
            media: components["schemas"]["MediaOut"];
            /** Timestamp S */
            timestamp_s: number;
            /** Rrf Score */
            rrf_score: number;
        };
        /**
         * Interpretation
         * @description What the engine understood, so a wrong guess is visible instead of mysterious.
         */
        Interpretation: {
            /** Query */
            query: string;
            /** Searched For */
            searched_for: string;
            /** Kind */
            kind: string | null;
            /** Excluded Concepts */
            excluded_concepts: string[];
            /** Applied Rules */
            applied_rules: string[];
            /** Safety Floor */
            safety_floor: boolean;
            /** Dropped Words */
            dropped_words: string[];
        };
        /** MediaDetail */
        MediaDetail: {
            media: components["schemas"]["MediaOut"];
            /** Description */
            description: string | null;
            /** Indoor Outdoor */
            indoor_outdoor: string | null;
            /** Time Of Day */
            time_of_day: string | null;
            /** People Count */
            people_count: string | null;
            /** Emotion */
            emotion: string | null;
            /** Uses */
            uses: string[];
            /** Avoid */
            avoid: string[];
            /** Tags */
            tags: components["schemas"]["TagOut"][];
            /** Probes */
            probes: components["schemas"]["ProbeScoreOut"][];
        };
        /** MediaOut */
        MediaOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Event */
            event: string | null;
            /** Kind */
            kind: string;
            /** Width */
            width: number | null;
            /** Height */
            height: number | null;
            /** Duration S */
            duration_s: number | null;
            /** Shot At */
            shot_at: string | null;
            /** Place */
            place: string | null;
            /** Activity */
            activity: string | null;
            /** Alcohol Visible */
            alcohol_visible: boolean;
        };
        /** ProbeOut */
        ProbeOut: {
            /** Name */
            name: string;
            /** Roc Auc */
            roc_auc: number;
            /** Average Precision */
            average_precision: number;
            /** N Positive */
            n_positive: number;
            /** Weak */
            weak: boolean;
        };
        /** ProbeScoreOut */
        ProbeScoreOut: {
            /** Name */
            name: string;
            /** P */
            p: number;
            /** Roc Auc */
            roc_auc: number;
            /** Weak */
            weak: boolean;
        };
        /** SearchRequest */
        SearchRequest: {
            /** Q */
            q: string;
            /** Limit */
            limit?: number | null;
        };
        /** SearchResponse */
        SearchResponse: {
            interpretation: components["schemas"]["Interpretation"];
            /** Hits */
            hits: components["schemas"]["HitOut"][];
            /** Took Ms */
            took_ms: number;
            /**
             * Cached
             * @default false
             */
            cached: boolean;
        };
        /** TagOut */
        TagOut: {
            /** Term */
            term: string;
            /** Source */
            source: string;
            /** Weight */
            weight: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    search_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_media_media__media_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_probes_probes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProbeOut"][];
                };
            };
        };
    };
    suggest_suggest_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
